version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: go-mysql-project
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project_db
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
  redis:
    image: redis:latest
    container_name: go-redis-project
    ports:
      - "6379:6379"
